### ISSUE TITLE
How to implement it?

### ISSUE THREAD

**Issue by swim89** [givebutter/laravel-custom-fields#13]
How to implement it in my project? I run `php artisan migrate` but `Nothing to migrate.` was promt.

What I need to add?

**Comment by swim89** [comment]
Please edit the readme.md file with the code below:

```
## Installation
`composer require givebutter/laravel-custom-fields`

### Laravel Service Provider

Add service provider in `app/config/app.php`

```php
'providers' => [
    Givebutter\LaravelCustomFields\LaravelCustomFieldsServiceProvider::class,
];
```

Publish configs, templates and run migrations.

```php
php artisan vendor:publish --provider="Givebutter\LaravelCustomFields\LaravelCustomFieldsServiceProvider"
```

This package publishes a few migrations. To run these in their default configuration, simply run `artisan migrate` after installation.
*You can customize the table names using config options. More on that later.*

```

**Comment by liran-co** [comment]
Thanks! I plan on updating the entire readme in the next couple days, sorry for the delay.
