### ISSUE TITLE
Laravel ^7.4 support

### ISSUE THREAD

**Issue by hardikpoojara** [givebutter/laravel-custom-fields#14]
Hello,

Please add laravel support above 7.4

Thanks !

![image](https://user-images.githubusercontent.com/16718829/84236931-1947fd80-ab16-11ea-8174-f88317f3a6ae.png)

**Comment by admirhusic** [comment]
Hello guys.  Is there any way to install this package on a Laravel V 7.20.0 project?

**Comment by vahidalvandi** [comment]
> Hello guys. Is there any way to install this package on a Laravel V 7.20.0 project?

i have this issue

**Comment by iFlyinq** [comment]
Yeah, and laravel ^8?

**Comment by liran-co** [comment]
https://github.com/givebutter/laravel-custom-fields/releases/tag/v0.1.8
